# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputForm(object):
    def setupUi(self, InputForm):
        InputForm.setObjectName("InputForm")
        InputForm.resize(422, 569)
        InputForm.setMinimumSize(QtCore.QSize(422, 569))
        InputForm.setMaximumSize(QtCore.QSize(422, 569))
        self.manufacturer_comboBox = QtWidgets.QComboBox(InputForm)
        self.manufacturer_comboBox.setGeometry(QtCore.QRect(260, 80, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.manufacturer_comboBox.setFont(font)
        self.manufacturer_comboBox.setObjectName("manufacturer_comboBox")
        self.manufacturer_comboBox.addItem("")
        self.manufacturer_comboBox.addItem("")
        self.manufacturer_comboBox.addItem("")
        self.label = QtWidgets.QLabel(InputForm)
        self.label.setGeometry(QtCore.QRect(10, 80, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.standard_comboBox = QtWidgets.QComboBox(InputForm)
        self.standard_comboBox.setGeometry(QtCore.QRect(260, 110, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.standard_comboBox.setFont(font)
        self.standard_comboBox.setObjectName("standard_comboBox")
        self.standard_comboBox.addItem("")
        self.standard_comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(InputForm)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.voltage_comboBox = QtWidgets.QComboBox(InputForm)
        self.voltage_comboBox.setGeometry(QtCore.QRect(260, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.voltage_comboBox.setFont(font)
        self.voltage_comboBox.setObjectName("voltage_comboBox")
        self.voltage_comboBox.addItem("")
        self.voltage_comboBox.addItem("")
        self.voltage_comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(InputForm)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(InputForm)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 221, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.CSA_comboBox = QtWidgets.QComboBox(InputForm)
        self.CSA_comboBox.setGeometry(QtCore.QRect(260, 260, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CSA_comboBox.setFont(font)
        self.CSA_comboBox.setObjectName("CSA_comboBox")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.CSA_comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(InputForm)
        self.label_5.setGeometry(QtCore.QRect(10, 290, 221, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.resistance_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.resistance_lineEdit.setGeometry(QtCore.QRect(260, 290, 151, 20))
        self.resistance_lineEdit.setObjectName("resistance_lineEdit")
        self.label_6 = QtWidgets.QLabel(InputForm)
        self.label_6.setGeometry(QtCore.QRect(10, 320, 221, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.inductance_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.inductance_lineEdit.setGeometry(QtCore.QRect(260, 320, 151, 20))
        self.inductance_lineEdit.setObjectName("inductance_lineEdit")
        self.label_7 = QtWidgets.QLabel(InputForm)
        self.label_7.setGeometry(QtCore.QRect(10, 350, 221, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.capacitance_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.capacitance_lineEdit.setGeometry(QtCore.QRect(260, 350, 151, 20))
        self.capacitance_lineEdit.setObjectName("capacitance_lineEdit")
        self.label_8 = QtWidgets.QLabel(InputForm)
        self.label_8.setGeometry(QtCore.QRect(10, 380, 231, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.sc_conductor_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.sc_conductor_lineEdit.setGeometry(QtCore.QRect(260, 380, 151, 20))
        self.sc_conductor_lineEdit.setObjectName("sc_conductor_lineEdit")
        self.sc_screen_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.sc_screen_lineEdit.setGeometry(QtCore.QRect(260, 410, 151, 20))
        self.sc_screen_lineEdit.setObjectName("sc_screen_lineEdit")
        self.label_9 = QtWidgets.QLabel(InputForm)
        self.label_9.setGeometry(QtCore.QRect(10, 410, 231, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.current_direct_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.current_direct_lineEdit.setGeometry(QtCore.QRect(260, 440, 151, 20))
        self.current_direct_lineEdit.setObjectName("current_direct_lineEdit")
        self.label_10 = QtWidgets.QLabel(InputForm)
        self.label_10.setGeometry(QtCore.QRect(10, 440, 241, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(InputForm)
        self.label_11.setGeometry(QtCore.QRect(10, 470, 241, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.current_ducted_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.current_ducted_lineEdit.setGeometry(QtCore.QRect(260, 470, 151, 20))
        self.current_ducted_lineEdit.setObjectName("current_ducted_lineEdit")
        self.current_open_lineEdit = QtWidgets.QLineEdit(InputForm)
        self.current_open_lineEdit.setGeometry(QtCore.QRect(260, 500, 151, 20))
        self.current_open_lineEdit.setObjectName("current_open_lineEdit")
        self.label_12 = QtWidgets.QLabel(InputForm)
        self.label_12.setGeometry(QtCore.QRect(10, 500, 241, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.reset_pushButton = QtWidgets.QPushButton(InputForm)
        self.reset_pushButton.setGeometry(QtCore.QRect(10, 530, 151, 31))
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.insert_pushButton = QtWidgets.QPushButton(InputForm)
        self.insert_pushButton.setGeometry(QtCore.QRect(260, 530, 151, 31))
        self.insert_pushButton.setObjectName("insert_pushButton")
        self.label_13 = QtWidgets.QLabel(InputForm)
        self.label_13.setGeometry(QtCore.QRect(40, 10, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.layout_comboBox = QtWidgets.QComboBox(InputForm)
        self.layout_comboBox.setGeometry(QtCore.QRect(260, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layout_comboBox.setFont(font)
        self.layout_comboBox.setObjectName("layout_comboBox")
        self.layout_comboBox.addItem("")
        self.layout_comboBox.addItem("")
        self.label_14 = QtWidgets.QLabel(InputForm)
        self.label_14.setGeometry(QtCore.QRect(10, 140, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(InputForm)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.material_comboBox = QtWidgets.QComboBox(InputForm)
        self.material_comboBox.setGeometry(QtCore.QRect(260, 170, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.material_comboBox.setFont(font)
        self.material_comboBox.setObjectName("material_comboBox")
        self.material_comboBox.addItem("")
        self.material_comboBox.addItem("")
        self.label_16 = QtWidgets.QLabel(InputForm)
        self.label_16.setGeometry(QtCore.QRect(10, 200, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.armour_comboBox = QtWidgets.QComboBox(InputForm)
        self.armour_comboBox.setGeometry(QtCore.QRect(260, 200, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.armour_comboBox.setFont(font)
        self.armour_comboBox.setObjectName("armour_comboBox")
        self.armour_comboBox.addItem("")
        self.armour_comboBox.addItem("")

        self.retranslateUi(InputForm)
        QtCore.QMetaObject.connectSlotsByName(InputForm)

    def retranslateUi(self, InputForm):
        _translate = QtCore.QCoreApplication.translate
        InputForm.setWindowTitle(_translate("InputForm", "Data Input for Cable Database - by Max Ellery"))
        self.manufacturer_comboBox.setItemText(0, _translate("InputForm", "Nexans"))
        self.manufacturer_comboBox.setItemText(1, _translate("InputForm", "BICC"))
        self.manufacturer_comboBox.setItemText(2, _translate("InputForm", "ElSewedey"))
        self.label.setText(_translate("InputForm", "Manufacturer"))
        self.standard_comboBox.setItemText(0, _translate("InputForm", "BS6622 / BS7835"))
        self.standard_comboBox.setItemText(1, _translate("InputForm", "BS7870-4.10 / IEC60502"))
        self.label_2.setText(_translate("InputForm", "Design Standard"))
        self.voltage_comboBox.setItemText(0, _translate("InputForm", "6.6"))
        self.voltage_comboBox.setItemText(1, _translate("InputForm", "11"))
        self.voltage_comboBox.setItemText(2, _translate("InputForm", "33"))
        self.label_3.setText(_translate("InputForm", "Voltage (kV)"))
        self.label_4.setText(_translate("InputForm", "Cross Sectional Area (mm2)"))
        self.CSA_comboBox.setItemText(0, _translate("InputForm", "25"))
        self.CSA_comboBox.setItemText(1, _translate("InputForm", "35"))
        self.CSA_comboBox.setItemText(2, _translate("InputForm", "50"))
        self.CSA_comboBox.setItemText(3, _translate("InputForm", "70"))
        self.CSA_comboBox.setItemText(4, _translate("InputForm", "95"))
        self.CSA_comboBox.setItemText(5, _translate("InputForm", "120"))
        self.CSA_comboBox.setItemText(6, _translate("InputForm", "150"))
        self.CSA_comboBox.setItemText(7, _translate("InputForm", "185"))
        self.CSA_comboBox.setItemText(8, _translate("InputForm", "240"))
        self.CSA_comboBox.setItemText(9, _translate("InputForm", "300"))
        self.CSA_comboBox.setItemText(10, _translate("InputForm", "400"))
        self.CSA_comboBox.setItemText(11, _translate("InputForm", "500"))
        self.CSA_comboBox.setItemText(12, _translate("InputForm", "630"))
        self.CSA_comboBox.setItemText(13, _translate("InputForm", "800"))
        self.CSA_comboBox.setItemText(14, _translate("InputForm", "1000"))
        self.label_5.setText(_translate("InputForm", "Resistance (ohm/km)"))
        self.label_6.setText(_translate("InputForm", "Inductance (mH/km)"))
        self.label_7.setText(_translate("InputForm", "Capacitance (uF/km)"))
        self.label_8.setText(_translate("InputForm", "1s SC Rating of conductor (kA)"))
        self.label_9.setText(_translate("InputForm", "1s SC Rating of screen (kA)"))
        self.label_10.setText(_translate("InputForm", "Current Rating Direct Buried (A)"))
        self.label_11.setText(_translate("InputForm", "Current Rating Ducted (A)"))
        self.label_12.setText(_translate("InputForm", "Current Rating Open Air (A)"))
        self.reset_pushButton.setText(_translate("InputForm", "Reset"))
        self.insert_pushButton.setText(_translate("InputForm", "Insert into Database"))
        self.label_13.setText(_translate("InputForm", "Data Input for Cable Database"))
        self.layout_comboBox.setItemText(0, _translate("InputForm", "Single Core"))
        self.layout_comboBox.setItemText(1, _translate("InputForm", "Three Core"))
        self.label_14.setText(_translate("InputForm", "Cable Layout"))
        self.label_15.setText(_translate("InputForm", "Material"))
        self.material_comboBox.setItemText(0, _translate("InputForm", "Copper"))
        self.material_comboBox.setItemText(1, _translate("InputForm", "Aluminium"))
        self.label_16.setText(_translate("InputForm", "Armour"))
        self.armour_comboBox.setItemText(0, _translate("InputForm", "Armoured"))
        self.armour_comboBox.setItemText(1, _translate("InputForm", "Unarmoured"))
